In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

In [2]:
df = pd.read_csv("final-df.csv")

In [3]:
df

Volcano Name  Max. VEI  Country  Volcanic_Region  Volcano_type  \
0                1         1        1                1             1   
1                2         4        2                2             1   
2                3         3        3                3             1   
3                4         1        1                1             1   
4                5         0        4                4             2   
...            ...       ...      ...              ...           ...   
7670           113         5       14               13             1   
7671           601         0        4               19            12   
7672           687         1       23               14            12   
7673           586         3       19                8             1   
7674           586         3       19                8             1   

        Summit  Year  Latitude_value  Longitude_value  Number Of Eruptions  \
0     0.649968    39          -7.540          110.446                   77   
1     0.495475    39          13.330          -61.180                    7   
2     0.543468    39          12.702          -87.004                   32   
3     0.596855    39          -7.942          112.950                   64   
4     0.495658    39          19.421         -155.287                   90   
...        ...   ...             ...              ...                  ...   
7670  0.564768     1         -39.157          175.632                    0   
7671  0.567236    32          43.420         -113.500                   13   
7672  0.488710    31          -4.889           31.933                    0   
7673  0.599689    30         -39.496          -71.722                    1   
7674  0.599689    28         -39.496          -71.722                    0   

      Number Of Eruptions per Country  
0                                1259  
1                                   7  
2                                 193  
3                                1259  
4                                 728  
...                               ...  
7670                                0  
7671                              153  
7672                                3  
7673                               34  
7674                               28  

[7675 rows x 11 columns]

In [4]:
temp_cols=df.columns.tolist()#list for cols
index=df.columns.get_loc("Max. VEI")#target column switch places with 1st column
new_cols=temp_cols[index:index+1] + temp_cols[0:index] + temp_cols[index+1:]
df=df[new_cols]
df


Max. VEI  Volcano Name  Country  Volcanic_Region  Volcano_type  \
0            1             1        1                1             1   
1            4             2        2                2             1   
2            3             3        3                3             1   
3            1             4        1                1             1   
4            0             5        4                4             2   
...        ...           ...      ...              ...           ...   
7670         5           113       14               13             1   
7671         0           601        4               19            12   
7672         1           687       23               14            12   
7673         3           586       19                8             1   
7674         3           586       19                8             1   

        Summit  Year  Latitude_value  Longitude_value  Number Of Eruptions  \
0     0.649968    39          -7.540          110.446                   77   
1     0.495475    39          13.330          -61.180                    7   
2     0.543468    39          12.702          -87.004                   32   
3     0.596855    39          -7.942          112.950                   64   
4     0.495658    39          19.421         -155.287                   90   
...        ...   ...             ...              ...                  ...   
7670  0.564768     1         -39.157          175.632                    0   
7671  0.567236    32          43.420         -113.500                   13   
7672  0.488710    31          -4.889           31.933                    0   
7673  0.599689    30         -39.496          -71.722                    1   
7674  0.599689    28         -39.496          -71.722                    0   

      Number Of Eruptions per Country  
0                                1259  
1                                   7  
2                                 193  
3                                1259  
4                                 728  
...                               ...  
7670                                0  
7671                              153  
7672                                3  
7673                               34  
7674                               28  

[7675 rows x 11 columns]

In [5]:
X = df.iloc[:, 1:10] #splitting the data to target column and the rest
y = df.iloc[:, 0]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)#training 80% testing 20%

In [6]:
def knn(X_train, y_train, X_test, y_test):#K nearest neighbors prediction model
    sc_X = StandardScaler()
    X_train = sc_X.fit_transform(X_train)
    X_test = sc_X.transform(X_test)
    
    classifier = KNeighborsClassifier(n_neighbors=7, p=2, metric='euclidean', n_jobs=-1)
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    return y_pred

def mlp(X_train, y_train, X_test, y_test): #MLP - nueron network model - found on scikit (great website!)
    clf = MLPClassifier().fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    return y_pred



In [7]:
def evaluate(X_train, y_train, X_test, y_test, classifier):#evaluating our score
    y_pred = classifier(X_train, y_train, X_test, y_test)
    print("%.6f" % precision_score(y_test, y_pred, average='micro'))
    print("%.6f" % recall_score(y_test, y_pred, average='micro'))
    print("%.6f" % f1_score(y_test, y_pred, average='micro'))
    print("%.6f" % accuracy_score(y_test, y_pred))
    print()
    print(confusion_matrix(y_test, y_pred))
    print('\n============================================')

evaluate(X_train, y_train, X_test, y_test, knn)
evaluate(X_train, y_train, X_test, y_test, mlp)


0.591531
0.591531
0.591531
0.591531

[[ 90  12  47  12   2   3   0   0]
 [ 19 113 114  12   1   0   0   0]
 [ 19  65 604  33   5   0   0   0]
 [  3  18 116  69  17   0   0   0]
 [  4   6  35  31  28   3   0   0]
 [  6   0   8   8  14   4   0   0]
 [  3   0   5   2   0   0   0   0]
 [  1   0   1   0   2   0   0   0]]

0.510098
0.510098
0.510098
0.510098

[[ 44   8  97  12   0   5   0   0]
 [  7  51 185  15   0   0   1   0]
 [ 18  39 629  37   1   1   1   0]
 [  1   4 162  51   2   3   0   0]
 [  2   1  64  37   1   2   0   0]
 [  0   0  16  16   1   7   0   0]
 [  0   0   8   2   0   0   0   0]
 [  0   0   3   1   0   0   0   0]]

0.454072
0.454072
0.454072
0.454072

[[  0   0   0   0   0   0   0   0   0]
 [  0  22  64  72   7   1   0   0   0]
 [  1   3  80 167   8   0   0   0   0]
 [  0   1 122 559  43   1   0   0   0]
 [  0   1  16 169  35   2   0   0   0]
 [  0   0  15  51  40   1   0   0   0]
 [  0   1   2  14  21   2   0   0   0]
 [  0   0   1   6   3   0   0   0   0]
 [  0   0   1